/**
 * NativPost SEO Tool — 1,000 Keyword Seed Script
 * ================================================
 * Run this ONCE after the SEO tool is deployed and the database is ready.
 *
 * Usage:
 *   node nativpost_keyword_seed.js
 *
 * It reads DB credentials from .env.local (same file as the SEO tool).
 * It uses ON DUPLICATE KEY UPDATE so it is safe to re-run.
 *
 * Place this file in the same directory as index.js (/opt/nativpost/NativPost-seo/)
 */

require('dotenv').config({ path: '.env.local' });
const mysql = require('mysql2/promise');

const DB = {
    host: process.env.DB_HOST || '127.0.0.1',
    port: Number(process.env.DB_PORT || 3307),
    user: process.env.DB_USER || 'nativpostseo',
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME || 'nativpost_seo',
};

// ---------------------------------------------------------------------------
// HELPER: priority score formula (mirrors the one inside index.js)
// ---------------------------------------------------------------------------
function priorityScore({ volume = 0, difficulty = 35, position = 50 }) {
    const vol = Math.min(Number(volume || 0) / 10000, 1) * 40;
    const diff = (1 - Math.min(Number(difficulty || 35) / 100, 1)) * 30;
    const pos = position <= 10 ? 30 : position <= 20 ? 20 : position <= 50 ? 10 : 0;
    return Math.round(vol + diff + pos);
}

// ---------------------------------------------------------------------------
// KEYWORD DATABASE — 1,000 keywords across 20 clusters
// Format: [keyword, cluster, volume, difficulty, intent]
//   volume  = estimated monthly searches (0 = unknown)
//   difficulty = 0–100 (lower = easier to rank)
//   intent  = commercial | informational | mixed
// ---------------------------------------------------------------------------
const KEYWORDS = [

    // ── 1. AI SOCIAL MEDIA TOOLS (core category) ─────────────────────────────
    ['ai social media content generator', 'AI Social Media Tools', 5400, 62, 'commercial'],
    ['ai social media tool', 'AI Social Media Tools', 4800, 60, 'commercial'],
    ['ai social media management', 'AI Social Media Tools', 3900, 58, 'commercial'],
    ['social media content generator', 'AI Social Media Tools', 8100, 65, 'commercial'],
    ['ai content generator for social media', 'AI Social Media Tools', 2900, 55, 'commercial'],
    ['best ai social media tool', 'AI Social Media Tools', 2400, 52, 'commercial'],
    ['ai social media manager', 'AI Social Media Tools', 2100, 50, 'commercial'],
    ['ai social media automation', 'AI Social Media Tools', 1800, 48, 'commercial'],
    ['ai social media post creator', 'AI Social Media Tools', 1600, 47, 'commercial'],
    ['ai social media scheduler', 'AI Social Media Tools', 1500, 45, 'commercial'],
    ['social media ai tool 2026', 'AI Social Media Tools', 1200, 40, 'commercial'],
    ['best ai tool for social media marketing', 'AI Social Media Tools', 1100, 42, 'commercial'],
    ['ai powered social media tool', 'AI Social Media Tools', 900, 38, 'commercial'],
    ['social media content ai tool', 'AI Social Media Tools', 800, 36, 'commercial'],
    ['ai content creator social media', 'AI Social Media Tools', 750, 35, 'commercial'],
    ['ai social media platform', 'AI Social Media Tools', 700, 34, 'commercial'],
    ['social media automation ai', 'AI Social Media Tools', 680, 33, 'commercial'],
    ['ai marketing tool social media', 'AI Social Media Tools', 650, 32, 'commercial'],
    ['ai generated social media posts', 'AI Social Media Tools', 620, 31, 'commercial'],
    ['social media ai assistant', 'AI Social Media Tools', 600, 30, 'commercial'],
    ['automated social media content generator', 'AI Social Media Tools', 580, 30, 'commercial'],
    ['ai social media content planner', 'AI Social Media Tools', 560, 29, 'commercial'],
    ['social media post generator ai free', 'AI Social Media Tools', 3200, 55, 'commercial'],
    ['ai tool for creating social media posts', 'AI Social Media Tools', 540, 28, 'commercial'],
    ['ai social media content writer', 'AI Social Media Tools', 520, 28, 'commercial'],
    ['social media post ai generator', 'AI Social Media Tools', 500, 27, 'commercial'],
    ['ai create social media content', 'AI Social Media Tools', 490, 27, 'commercial'],
    ['best free ai social media tool', 'AI Social Media Tools', 2100, 50, 'commercial'],
    ['ai for small business social media', 'AI Social Media Tools', 480, 26, 'commercial'],
    ['social media content creation ai', 'AI Social Media Tools', 470, 26, 'commercial'],
    ['ai write social media posts', 'AI Social Media Tools', 460, 25, 'commercial'],
    ['automatic social media post generator', 'AI Social Media Tools', 450, 25, 'commercial'],
    ['smart social media content tool', 'AI Social Media Tools', 430, 24, 'commercial'],
    ['ai generate posts for instagram facebook', 'AI Social Media Tools', 420, 24, 'commercial'],
    ['social media content batch generator', 'AI Social Media Tools', 400, 23, 'commercial'],
    ['ai social content creation platform', 'AI Social Media Tools', 390, 23, 'commercial'],
    ['social media auto post ai', 'AI Social Media Tools', 380, 22, 'commercial'],
    ['ai tool batch social media', 'AI Social Media Tools', 370, 22, 'commercial'],
    ['social media post generator no login', 'AI Social Media Tools', 1400, 42, 'commercial'],
    ['ai write captions for social media', 'AI Social Media Tools', 360, 21, 'commercial'],
    ['publish to all social media at once ai', 'AI Social Media Tools', 350, 21, 'commercial'],
    ['social media content suite ai', 'AI Social Media Tools', 340, 20, 'commercial'],
    ['ai that manages your social media', 'AI Social Media Tools', 330, 20, 'commercial'],
    ['ai create post for all platforms', 'AI Social Media Tools', 320, 19, 'commercial'],
    ['social media productivity ai tool', 'AI Social Media Tools', 310, 19, 'commercial'],
    ['ai social post builder', 'AI Social Media Tools', 300, 18, 'commercial'],
    ['content generator for all social platforms', 'AI Social Media Tools', 295, 18, 'commercial'],
    ['ai marketing content generator', 'AI Social Media Tools', 290, 17, 'commercial'],
    ['all in one social media ai tool', 'AI Social Media Tools', 285, 17, 'commercial'],
    ['multi-platform social media post creator ai', 'AI Social Media Tools', 280, 17, 'commercial'],

    // ── 2. BRAND VOICE ────────────────────────────────────────────────────────
    ['brand voice ai', 'Brand Voice', 1900, 38, 'commercial'],
    ['ai brand voice generator', 'Brand Voice', 1600, 36, 'commercial'],
    ['brand voice tool', 'Brand Voice', 1400, 34, 'commercial'],
    ['consistent brand voice social media', 'Brand Voice', 1200, 32, 'commercial'],
    ['maintain brand voice ai', 'Brand Voice', 900, 30, 'commercial'],
    ['brand voice consistency tool', 'Brand Voice', 800, 28, 'commercial'],
    ['how to create a brand voice', 'Brand Voice', 2700, 35, 'informational'],
    ['what is brand voice', 'Brand Voice', 3200, 25, 'informational'],
    ['brand voice guide for social media', 'Brand Voice', 720, 26, 'informational'],
    ['brand voice examples social media', 'Brand Voice', 1100, 28, 'informational'],
    ['tone of voice ai tool', 'Brand Voice', 680, 26, 'commercial'],
    ['ai that learns your brand voice', 'Brand Voice', 640, 24, 'commercial'],
    ['brand voice for instagram', 'Brand Voice', 600, 23, 'mixed'],
    ['brand voice for linkedin', 'Brand Voice', 580, 23, 'mixed'],
    ['brand voice for tiktok', 'Brand Voice', 560, 22, 'mixed'],
    ['ai write in brand voice', 'Brand Voice', 540, 22, 'commercial'],
    ['brand voice generator free', 'Brand Voice', 1800, 38, 'commercial'],
    ['how to keep brand voice consistent', 'Brand Voice', 520, 21, 'informational'],
    ['brand voice document template', 'Brand Voice', 2100, 30, 'informational'],
    ['brand voice vs brand tone', 'Brand Voice', 900, 20, 'informational'],
    ['developing a brand voice', 'Brand Voice', 1500, 28, 'informational'],
    ['brand voice training ai', 'Brand Voice', 500, 20, 'commercial'],
    ['ai maintain tone of voice', 'Brand Voice', 480, 20, 'commercial'],
    ['brand identity ai tool', 'Brand Voice', 460, 19, 'commercial'],
    ['how to define brand voice small business', 'Brand Voice', 440, 18, 'informational'],
    ['content that sounds like your brand', 'Brand Voice', 420, 18, 'commercial'],
    ['ai write like my brand', 'Brand Voice', 400, 17, 'commercial'],
    ['brand voice checklist', 'Brand Voice', 1900, 22, 'informational'],
    ['brand voice for startup', 'Brand Voice', 380, 17, 'commercial'],
    ['brand voice scale social media', 'Brand Voice', 360, 16, 'commercial'],
    ['ai content that does not sound like ai', 'Brand Voice', 2400, 32, 'commercial'],
    ['non-generic ai social media posts', 'Brand Voice', 320, 15, 'commercial'],
    ['ai post that sounds human', 'Brand Voice', 300, 15, 'commercial'],
    ['anti-slop ai content', 'Brand Voice', 280, 14, 'commercial'],
    ['social media content that sounds authentic', 'Brand Voice', 260, 14, 'informational'],

    // ── 3. COMPETITOR ALTERNATIVES ────────────────────────────────────────────
    ['ocoya alternative', 'Competitor Alternatives', 1400, 32, 'commercial'],
    ['nativpost vs ocoya', 'Competitor Alternatives', 500, 20, 'commercial'],
    ['buffer alternative ai', 'Competitor Alternatives', 2200, 40, 'commercial'],
    ['hootsuite alternative small business', 'Competitor Alternatives', 1900, 38, 'commercial'],
    ['jasper alternative social media', 'Competitor Alternatives', 1100, 30, 'commercial'],
    ['predis ai alternative', 'Competitor Alternatives', 800, 25, 'commercial'],
    ['later alternative ai', 'Competitor Alternatives', 900, 26, 'commercial'],
    ['feedhive alternative', 'Competitor Alternatives', 600, 22, 'commercial'],
    ['socialbee alternative', 'Competitor Alternatives', 700, 23, 'commercial'],
    ['contentstudio alternative', 'Competitor Alternatives', 650, 22, 'commercial'],
    ['sprout social alternative affordable', 'Competitor Alternatives', 1200, 32, 'commercial'],
    ['buffer vs hootsuite vs ai tool', 'Competitor Alternatives', 1600, 38, 'informational'],
    ['ocoya review 2026', 'Competitor Alternatives', 700, 24, 'informational'],
    ['hootsuite too expensive alternatives', 'Competitor Alternatives', 900, 28, 'commercial'],
    ['cancel hootsuite switch to', 'Competitor Alternatives', 500, 20, 'commercial'],
    ['buffer pricing too high alternative', 'Competitor Alternatives', 800, 26, 'commercial'],
    ['best hootsuite replacement 2026', 'Competitor Alternatives', 1100, 30, 'commercial'],
    ['best buffer alternative 2026', 'Competitor Alternatives', 1300, 32, 'commercial'],
    ['nativpost vs buffer', 'Competitor Alternatives', 400, 18, 'commercial'],
    ['nativpost vs predis', 'Competitor Alternatives', 350, 17, 'commercial'],
    ['best social media tool not buffer', 'Competitor Alternatives', 600, 22, 'commercial'],
    ['affordable hootsuite alternative', 'Competitor Alternatives', 1000, 29, 'commercial'],
    ['ai scheduling tool better than ocoya', 'Competitor Alternatives', 450, 19, 'commercial'],
    ['social media tool with better ai than buffer', 'Competitor Alternatives', 380, 17, 'commercial'],
    ['jasper too expensive alternative', 'Competitor Alternatives', 700, 23, 'commercial'],
    ['sprout social too expensive', 'Competitor Alternatives', 1100, 30, 'commercial'],
    ['best alternative to sprout social', 'Competitor Alternatives', 1400, 33, 'commercial'],
    ['social media tool with brand voice', 'Competitor Alternatives', 560, 21, 'commercial'],
    ['ai social media that is not generic', 'Competitor Alternatives', 480, 19, 'commercial'],
    ['ocoya pricing review', 'Competitor Alternatives', 550, 21, 'informational'],

    // ── 4. INSTAGRAM CONTENT ─────────────────────────────────────────────────
    ['ai caption generator instagram', 'Instagram Content', 8200, 65, 'commercial'],
    ['ai instagram post generator', 'Instagram Content', 5800, 60, 'commercial'],
    ['instagram caption generator', 'Instagram Content', 9500, 68, 'commercial'],
    ['auto generate instagram captions', 'Instagram Content', 2800, 52, 'commercial'],
    ['ai write instagram captions', 'Instagram Content', 2400, 50, 'commercial'],
    ['best instagram caption generator ai', 'Instagram Content', 2100, 48, 'commercial'],
    ['instagram content generator ai', 'Instagram Content', 1900, 46, 'commercial'],
    ['ai for instagram marketing', 'Instagram Content', 1700, 44, 'commercial'],
    ['instagram reel caption generator ai', 'Instagram Content', 1500, 42, 'commercial'],
    ['ai instagram scheduler', 'Instagram Content', 1400, 42, 'commercial'],
    ['generate instagram posts automatically', 'Instagram Content', 1300, 40, 'commercial'],
    ['instagram caption ai free', 'Instagram Content', 3400, 58, 'commercial'],
    ['ai generate hashtags instagram', 'Instagram Content', 2600, 52, 'commercial'],
    ['ai instagram content plan', 'Instagram Content', 1100, 38, 'commercial'],
    ['brand-matched instagram captions ai', 'Instagram Content', 800, 32, 'commercial'],
    ['instagram post ideas generator ai', 'Instagram Content', 2200, 48, 'mixed'],
    ['best caption generator for instagram 2026', 'Instagram Content', 1800, 44, 'commercial'],
    ['ai instagram bio generator', 'Instagram Content', 1600, 42, 'commercial'],
    ['instagram carousel caption ai', 'Instagram Content', 900, 34, 'commercial'],
    ['ai tool for instagram growth', 'Instagram Content', 1200, 38, 'commercial'],
    ['auto post to instagram ai', 'Instagram Content', 1000, 36, 'commercial'],
    ['instagram content strategy ai', 'Instagram Content', 850, 33, 'informational'],
    ['ai schedule instagram posts', 'Instagram Content', 1100, 37, 'commercial'],
    ['instagram story caption generator', 'Instagram Content', 1300, 39, 'commercial'],
    ['create instagram posts with ai', 'Instagram Content', 1500, 41, 'commercial'],

    // ── 5. LINKEDIN CONTENT ───────────────────────────────────────────────────
    ['linkedin post generator ai', 'LinkedIn Content', 5400, 58, 'commercial'],
    ['ai linkedin post writer', 'LinkedIn Content', 3200, 52, 'commercial'],
    ['best linkedin post generator', 'LinkedIn Content', 2800, 50, 'commercial'],
    ['ai write linkedin posts', 'LinkedIn Content', 2400, 48, 'commercial'],
    ['linkedin content generator', 'LinkedIn Content', 2100, 46, 'commercial'],
    ['linkedin ai post creator', 'LinkedIn Content', 1900, 44, 'commercial'],
    ['auto generate linkedin content', 'LinkedIn Content', 1600, 42, 'commercial'],
    ['ai for linkedin marketing', 'LinkedIn Content', 1400, 40, 'commercial'],
    ['linkedin thought leadership ai tool', 'LinkedIn Content', 1200, 38, 'commercial'],
    ['linkedin caption generator', 'LinkedIn Content', 1800, 44, 'commercial'],
    ['ai linkedin scheduler', 'LinkedIn Content', 1100, 37, 'commercial'],
    ['linkedin post ideas generator', 'LinkedIn Content', 2200, 46, 'mixed'],
    ['professional linkedin posts ai', 'LinkedIn Content', 900, 33, 'commercial'],
    ['linkedin company page ai content', 'LinkedIn Content', 800, 31, 'commercial'],
    ['ai tool for linkedin growth', 'LinkedIn Content', 750, 30, 'commercial'],
    ['schedule linkedin posts automatically', 'LinkedIn Content', 1000, 35, 'commercial'],
    ['linkedin article generator ai', 'LinkedIn Content', 1500, 40, 'commercial'],
    ['ai for b2b linkedin content', 'LinkedIn Content', 700, 29, 'commercial'],
    ['linkedin post generator free 2026', 'LinkedIn Content', 2600, 50, 'commercial'],
    ['best ai for linkedin', 'LinkedIn Content', 1700, 42, 'commercial'],
    ['create linkedin content with ai', 'LinkedIn Content', 1300, 39, 'commercial'],
    ['linkedin brand voice ai', 'LinkedIn Content', 600, 26, 'commercial'],
    ['ai that writes linkedin posts in my voice', 'LinkedIn Content', 550, 25, 'commercial'],
    ['linkedin content strategy ai tool', 'LinkedIn Content', 480, 23, 'informational'],
    ['generate linkedin posts automatically', 'LinkedIn Content', 1400, 40, 'commercial'],

    // ── 6. TIKTOK CONTENT ─────────────────────────────────────────────────────
    ['ai tiktok caption generator', 'TikTok Content', 4200, 55, 'commercial'],
    ['tiktok content generator ai', 'TikTok Content', 3100, 52, 'commercial'],
    ['ai generate tiktok captions', 'TikTok Content', 2400, 48, 'commercial'],
    ['tiktok post generator ai', 'TikTok Content', 2100, 46, 'commercial'],
    ['best tiktok caption generator', 'TikTok Content', 3500, 54, 'commercial'],
    ['ai for tiktok marketing', 'TikTok Content', 1800, 42, 'commercial'],
    ['tiktok ai content creator', 'TikTok Content', 1600, 40, 'commercial'],
    ['ai write tiktok scripts', 'TikTok Content', 1400, 38, 'commercial'],
    ['tiktok content strategy ai', 'TikTok Content', 1100, 35, 'informational'],
    ['auto generate tiktok content', 'TikTok Content', 900, 32, 'commercial'],
    ['tiktok hashtag generator ai', 'TikTok Content', 2800, 50, 'commercial'],
    ['ai for tiktok businesses', 'TikTok Content', 750, 30, 'commercial'],
    ['schedule tiktok posts automatically', 'TikTok Content', 1200, 37, 'commercial'],
    ['tiktok post ideas ai', 'TikTok Content', 1900, 43, 'mixed'],
    ['tiktok brand voice', 'TikTok Content', 600, 25, 'informational'],
    ['ai tiktok scheduler', 'TikTok Content', 800, 31, 'commercial'],
    ['tiktok small business marketing ai', 'TikTok Content', 550, 24, 'commercial'],
    ['create tiktok content with ai', 'TikTok Content', 1300, 38, 'commercial'],
    ['viral tiktok caption generator', 'TikTok Content', 2100, 46, 'commercial'],
    ['ai tiktok video script generator', 'TikTok Content', 1700, 41, 'commercial'],

    // ── 7. FACEBOOK CONTENT ───────────────────────────────────────────────────
    ['facebook post generator ai', 'Facebook Content', 4100, 58, 'commercial'],
    ['ai facebook content creator', 'Facebook Content', 2600, 50, 'commercial'],
    ['facebook caption generator ai', 'Facebook Content', 3200, 52, 'commercial'],
    ['ai write facebook posts', 'Facebook Content', 2100, 46, 'commercial'],
    ['auto generate facebook content', 'Facebook Content', 1700, 42, 'commercial'],
    ['facebook post ideas generator ai', 'Facebook Content', 2400, 48, 'mixed'],
    ['ai for facebook business page', 'Facebook Content', 1500, 40, 'commercial'],
    ['facebook page ai content tool', 'Facebook Content', 1200, 37, 'commercial'],
    ['ai schedule facebook posts', 'Facebook Content', 1100, 36, 'commercial'],
    ['facebook ad caption generator ai', 'Facebook Content', 1900, 44, 'commercial'],
    ['facebook content strategy ai', 'Facebook Content', 900, 33, 'informational'],
    ['ai facebook marketing tool', 'Facebook Content', 800, 31, 'commercial'],
    ['facebook and instagram post generator ai', 'Facebook Content', 1400, 39, 'commercial'],
    ['auto post facebook ai tool', 'Facebook Content', 700, 29, 'commercial'],
    ['create facebook posts automatically', 'Facebook Content', 1600, 41, 'commercial'],

    // ── 8. VIDEO GENERATION ───────────────────────────────────────────────────
    ['ai social media video generator', 'Video Generation', 3200, 52, 'commercial'],
    ['ugc ad generator ai', 'Video Generation', 2100, 45, 'commercial'],
    ['ai video content for social media', 'Video Generation', 2800, 50, 'commercial'],
    ['ai generate social media videos', 'Video Generation', 2400, 48, 'commercial'],
    ['ai video creator for instagram', 'Video Generation', 2200, 46, 'commercial'],
    ['ai tiktok video generator', 'Video Generation', 2900, 51, 'commercial'],
    ['ugc style video generator ai', 'Video Generation', 1600, 40, 'commercial'],
    ['ai create reel automatically', 'Video Generation', 1400, 38, 'commercial'],
    ['short video generator ai', 'Video Generation', 2600, 50, 'commercial'],
    ['ai voiceover social media video', 'Video Generation', 1200, 36, 'commercial'],
    ['text to video social media ai', 'Video Generation', 3400, 54, 'commercial'],
    ['ai animated social media video', 'Video Generation', 1100, 35, 'commercial'],
    ['ai data story video generator', 'Video Generation', 800, 30, 'commercial'],
    ['social media video ai tool', 'Video Generation', 2100, 45, 'commercial'],
    ['ai slideshow video generator', 'Video Generation', 1800, 42, 'commercial'],
    ['ai reels generator for brands', 'Video Generation', 1500, 39, 'commercial'],
    ['make ugc ads with ai', 'Video Generation', 1900, 43, 'commercial'],
    ['ai create marketing video', 'Video Generation', 2300, 47, 'commercial'],
    ['ai video for small business social media', 'Video Generation', 900, 32, 'commercial'],
    ['vertical video creator ai', 'Video Generation', 1300, 37, 'commercial'],
    ['ai video branding tool', 'Video Generation', 700, 28, 'commercial'],
    ['automatic reel creator ai', 'Video Generation', 1100, 35, 'commercial'],
    ['ai video caption sync', 'Video Generation', 800, 30, 'commercial'],
    ['social video generator brands', 'Video Generation', 650, 27, 'commercial'],
    ['ai create videos from text social media', 'Video Generation', 1700, 41, 'commercial'],

    // ── 9. SOCIAL MEDIA SCHEDULING ────────────────────────────────────────────
    ['social media scheduling tool', 'Social Media Scheduling', 6800, 65, 'commercial'],
    ['best social media scheduler 2026', 'Social Media Scheduling', 4200, 58, 'commercial'],
    ['auto publish social media', 'Social Media Scheduling', 2400, 48, 'commercial'],
    ['social media calendar tool', 'Social Media Scheduling', 3100, 52, 'commercial'],
    ['schedule posts to all social media', 'Social Media Scheduling', 2800, 50, 'commercial'],
    ['automated social media posting', 'Social Media Scheduling', 2200, 46, 'commercial'],
    ['social media post scheduler app', 'Social Media Scheduling', 3600, 54, 'commercial'],
    ['cross platform social media scheduler', 'Social Media Scheduling', 1900, 43, 'commercial'],
    ['bulk schedule social media posts', 'Social Media Scheduling', 1600, 40, 'commercial'],
    ['social media planner tool', 'Social Media Scheduling', 2900, 51, 'commercial'],
    ['schedule instagram linkedin tiktok', 'Social Media Scheduling', 1400, 38, 'commercial'],
    ['ai social media calendar', 'Social Media Scheduling', 1800, 42, 'commercial'],
    ['auto schedule social media content', 'Social Media Scheduling', 1500, 39, 'commercial'],
    ['publish social media automatically', 'Social Media Scheduling', 1200, 36, 'commercial'],
    ['best social media planner app 2026', 'Social Media Scheduling', 2100, 45, 'commercial'],
    ['social media content calendar ai', 'Social Media Scheduling', 1700, 41, 'commercial'],
    ['free social media scheduler', 'Social Media Scheduling', 5100, 62, 'commercial'],
    ['social media management scheduler', 'Social Media Scheduling', 2600, 49, 'commercial'],
    ['schedule posts weeks in advance', 'Social Media Scheduling', 900, 32, 'commercial'],
    ['social media queue tool', 'Social Media Scheduling', 1100, 35, 'commercial'],
    ['ai schedule and publish social media', 'Social Media Scheduling', 750, 29, 'commercial'],
    ['content calendar with publishing tool', 'Social Media Scheduling', 680, 28, 'commercial'],
    ['best time to post ai tool', 'Social Media Scheduling', 1300, 37, 'commercial'],
    ['social media scheduling with ai content', 'Social Media Scheduling', 600, 25, 'commercial'],
    ['publish multiple platforms one tool', 'Social Media Scheduling', 550, 24, 'commercial'],

    // ── 10. SMALL BUSINESS SOCIAL MEDIA ──────────────────────────────────────
    ['social media tool for small business', 'Small Business Social', 4400, 55, 'commercial'],
    ['best social media tool small business 2026', 'Small Business Social', 2800, 50, 'commercial'],
    ['affordable social media management tool', 'Small Business Social', 2100, 45, 'commercial'],
    ['small business social media manager', 'Small Business Social', 1900, 43, 'commercial'],
    ['social media management small business', 'Small Business Social', 3200, 52, 'commercial'],
    ['cheap social media management tool', 'Small Business Social', 1600, 40, 'commercial'],
    ['small business instagram marketing tool', 'Small Business Social', 1400, 38, 'commercial'],
    ['social media for local business ai', 'Small Business Social', 1200, 36, 'commercial'],
    ['ai social media for startups', 'Small Business Social', 900, 32, 'commercial'],
    ['small business social media content ideas', 'Small Business Social', 2400, 47, 'informational'],
    ['social media ai for entrepreneurs', 'Small Business Social', 800, 30, 'commercial'],
    ['budget social media tool', 'Small Business Social', 750, 29, 'commercial'],
    ['diy social media management tool', 'Small Business Social', 700, 28, 'commercial'],
    ['solo founder social media tool', 'Small Business Social', 600, 25, 'commercial'],
    ['social media without a team', 'Small Business Social', 550, 24, 'informational'],
    ['social media tool without agency', 'Small Business Social', 500, 22, 'commercial'],
    ['manage social media yourself ai', 'Small Business Social', 480, 22, 'commercial'],
    ['one person social media manager tool', 'Small Business Social', 460, 21, 'commercial'],
    ['small team social media tool', 'Small Business Social', 440, 21, 'commercial'],
    ['social media content without designer', 'Small Business Social', 420, 20, 'informational'],
    ['save time on social media small business', 'Small Business Social', 2100, 44, 'informational'],
    ['outsource social media with ai', 'Small Business Social', 380, 19, 'commercial'],
    ['professional social media on budget', 'Small Business Social', 360, 18, 'commercial'],
    ['how small business can compete on social', 'Small Business Social', 340, 17, 'informational'],
    ['social media roi small business', 'Small Business Social', 1600, 40, 'informational'],

    // ── 11. AFRICA MARKET ────────────────────────────────────────────────────
    ['social media tool nigeria', 'Africa Market', 1900, 28, 'commercial'],
    ['social media management kenya', 'Africa Market', 1600, 25, 'commercial'],
    ['best social media tool south africa', 'Africa Market', 1400, 24, 'commercial'],
    ['ai social media tool africa', 'Africa Market', 1200, 22, 'commercial'],
    ['social media tool ghana', 'Africa Market', 900, 20, 'commercial'],
    ['best social media tool lagos', 'Africa Market', 800, 18, 'commercial'],
    ['paystack social media marketing', 'Africa Market', 600, 16, 'commercial'],
    ['social media management nairobi', 'Africa Market', 700, 17, 'commercial'],
    ['ai content tool africa', 'Africa Market', 550, 15, 'commercial'],
    ['social media scheduler africa', 'Africa Market', 500, 15, 'commercial'],
    ['nigerian business social media tool', 'Africa Market', 750, 17, 'commercial'],
    ['best marketing tool for nigerian smes', 'Africa Market', 480, 14, 'commercial'],
    ['content marketing tool accra', 'Africa Market', 440, 13, 'commercial'],
    ['african brand social media tool', 'Africa Market', 420, 13, 'commercial'],
    ['social media management johannesburg', 'Africa Market', 680, 16, 'commercial'],
    ['cheap social media tool nigeria', 'Africa Market', 900, 19, 'commercial'],
    ['ai tool for african businesses', 'Africa Market', 400, 13, 'commercial'],
    ['pay in naira for social media tool', 'Africa Market', 380, 12, 'commercial'],
    ['social media tool paying with paystack', 'Africa Market', 360, 12, 'commercial'],
    ['social media marketing for smbs africa', 'Africa Market', 340, 12, 'informational'],
    ['grow business on instagram africa', 'Africa Market', 1200, 22, 'informational'],
    ['grow business on linkedin nigeria', 'Africa Market', 800, 18, 'informational'],
    ['african startup social media strategy', 'Africa Market', 600, 16, 'informational'],
    ['social media strategy for nigerian brands', 'Africa Market', 550, 15, 'informational'],
    ['content creation tool for african brands', 'Africa Market', 320, 12, 'commercial'],

    // ── 12. AGENCY SOCIAL MEDIA MANAGEMENT ───────────────────────────────────
    ['social media tool for agencies', 'Agency Tools', 2800, 50, 'commercial'],
    ['best social media management agency tool', 'Agency Tools', 2100, 46, 'commercial'],
    ['white label social media tool', 'Agency Tools', 1800, 42, 'commercial'],
    ['agency social media scheduler', 'Agency Tools', 1600, 40, 'commercial'],
    ['manage multiple clients social media', 'Agency Tools', 1400, 38, 'commercial'],
    ['social media agency software 2026', 'Agency Tools', 1200, 36, 'commercial'],
    ['ai tool for social media agencies', 'Agency Tools', 1100, 35, 'commercial'],
    ['multi client social media management', 'Agency Tools', 900, 32, 'commercial'],
    ['scale social media content for clients', 'Agency Tools', 800, 30, 'commercial'],
    ['agency tier social media tool ai', 'Agency Tools', 700, 28, 'commercial'],
    ['social media reporting tool agency', 'Agency Tools', 1500, 39, 'commercial'],
    ['manage 10 clients social media', 'Agency Tools', 600, 25, 'commercial'],
    ['unlimited social media posts tool', 'Agency Tools', 1300, 37, 'commercial'],
    ['team collaboration social media tool', 'Agency Tools', 1700, 41, 'commercial'],
    ['approval workflow social media agency', 'Agency Tools', 900, 32, 'commercial'],
    ['multi brand social media dashboard', 'Agency Tools', 750, 29, 'commercial'],
    ['social media tool for marketing agencies', 'Agency Tools', 1900, 43, 'commercial'],
    ['content review workflow social media', 'Agency Tools', 650, 26, 'commercial'],
    ['ai automate client social media content', 'Agency Tools', 580, 24, 'commercial'],
    ['best tool for managing client socials', 'Agency Tools', 520, 22, 'commercial'],

    // ── 13. GRAPHICS / VISUAL CONTENT ────────────────────────────────────────
    ['ai social media graphic generator', 'Visual Content', 2200, 46, 'commercial'],
    ['ai create social media graphics', 'AI Social Media Tools', 1900, 43, 'commercial'],
    ['social media image generator ai', 'Visual Content', 2600, 49, 'commercial'],
    ['quote card generator ai', 'Visual Content', 1400, 38, 'commercial'],
    ['ai branded content creator', 'Visual Content', 1100, 35, 'commercial'],
    ['ai social media design tool', 'Visual Content', 1600, 40, 'commercial'],
    ['stat card social media generator', 'Visual Content', 800, 30, 'commercial'],
    ['announcement card generator', 'Visual Content', 700, 28, 'commercial'],
    ['carousel slide generator ai', 'Visual Content', 1200, 36, 'commercial'],
    ['ai generate branded images social media', 'Visual Content', 900, 32, 'commercial'],
    ['social media post with image ai', 'Visual Content', 1800, 42, 'commercial'],
    ['ai create graphics for instagram', 'Visual Content', 2100, 45, 'commercial'],
    ['brand overlay image ai', 'Visual Content', 600, 24, 'commercial'],
    ['ai social media visual content', 'Visual Content', 1000, 34, 'commercial'],
    ['professional social media images ai', 'Visual Content', 750, 29, 'commercial'],
    ['design social media posts with ai', 'Visual Content', 1500, 39, 'commercial'],
    ['ai canva alternative social media', 'Visual Content', 1700, 41, 'commercial'],
    ['ai make instagram graphics automatically', 'Visual Content', 950, 33, 'commercial'],
    ['linkedin banner generator ai', 'Visual Content', 1300, 37, 'commercial'],
    ['social media infographic generator ai', 'Visual Content', 1100, 35, 'commercial'],

    // ── 14. CONTENT QUALITY & ANTI-SLOP ──────────────────────────────────────
    ['how to make ai content sound human', 'Content Quality', 3400, 42, 'informational'],
    ['ai content that does not sound like ai', 'Content Quality', 2800, 38, 'commercial'],
    ['avoid generic ai captions', 'Content Quality', 1600, 32, 'informational'],
    ['non-generic social media content', 'Content Quality', 1200, 30, 'commercial'],
    ['ai content quality filter', 'Content Quality', 900, 28, 'commercial'],
    ['high quality ai social media posts', 'Content Quality', 1400, 34, 'commercial'],
    ['social media content that engages', 'Content Quality', 2200, 38, 'informational'],
    ['engaging social media captions ai', 'Content Quality', 1800, 36, 'commercial'],
    ['authentic social media content ai', 'Content Quality', 1100, 30, 'commercial'],
    ['ai posts that feel personal', 'Content Quality', 800, 26, 'commercial'],
    ['avoid corporate speak social media', 'Content Quality', 700, 24, 'informational'],
    ['social media content that converts', 'Content Quality', 2100, 38, 'informational'],
    ['how to write good social media posts', 'Content Quality', 4100, 45, 'informational'],
    ['social media writing tips 2026', 'Content Quality', 1900, 35, 'informational'],
    ['content engagement tactics social media', 'Content Quality', 1600, 33, 'informational'],
    ['what makes a good social media post', 'Content Quality', 3200, 42, 'informational'],
    ['ai content review workflow', 'Content Quality', 600, 22, 'commercial'],
    ['social media quality control ai', 'Content Quality', 550, 22, 'commercial'],
    ['team approval social media content', 'Content Quality', 500, 21, 'commercial'],
    ['review social media posts before publish', 'Content Quality', 480, 20, 'commercial'],

    // ── 15. HOW-TO / EDUCATIONAL ─────────────────────────────────────────────
    ['how to use ai for social media marketing', 'How To / Educational', 5400, 42, 'informational'],
    ['how to create consistent social media', 'How To / Educational', 3200, 38, 'informational'],
    ['how to build brand voice social media', 'How To / Educational', 2800, 35, 'informational'],
    ['how to grow business on social media', 'How To / Educational', 6100, 48, 'informational'],
    ['how to automate social media posting', 'How To / Educational', 3600, 40, 'informational'],
    ['how to schedule posts on instagram', 'How To / Educational', 4200, 42, 'informational'],
    ['how to post on multiple platforms at once', 'How To / Educational', 2900, 37, 'informational'],
    ['how to create social media content plan', 'How To / Educational', 3400, 39, 'informational'],
    ['how to write captions that convert', 'How To / Educational', 2200, 34, 'informational'],
    ['social media content ideas for business', 'How To / Educational', 4800, 44, 'informational'],
    ['how to save time on social media', 'How To / Educational', 2600, 36, 'informational'],
    ['social media for business beginners', 'How To / Educational', 3100, 38, 'informational'],
    ['how to go viral on linkedin', 'How To / Educational', 4400, 43, 'informational'],
    ['how to get more instagram followers 2026', 'How To / Educational', 5900, 48, 'informational'],
    ['how to create a social media strategy', 'How To / Educational', 5200, 46, 'informational'],
    ['content creation workflow for teams', 'How To / Educational', 1800, 32, 'informational'],
    ['how to repurpose content social media', 'How To / Educational', 2400, 35, 'informational'],
    ['social media tips for small business 2026', 'How To / Educational', 2900, 37, 'informational'],
    ['how to create ugc ads for small business', 'How To / Educational', 1600, 30, 'informational'],
    ['ai social media beginner guide', 'How To / Educational', 1200, 27, 'informational'],
    ['social media content calendar template', 'How To / Educational', 5600, 47, 'informational'],
    ['how to outsource social media with ai', 'How To / Educational', 1100, 26, 'informational'],
    ['social media growth hacks 2026', 'How To / Educational', 3800, 41, 'informational'],
    ['content batching social media guide', 'How To / Educational', 1400, 28, 'informational'],
    ['how to measure social media roi', 'How To / Educational', 3200, 38, 'informational'],

    // ── 16. NATIVPOST BRAND KEYWORDS ─────────────────────────────────────────
    ['nativpost review', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost pricing', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost social media tool', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost ai tool', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost vs competitors', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost alternatives', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost starter plan', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost growth plan', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost agency plan', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost trial', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost free trial', 'NativPost Brand', 0, 10, 'commercial'],
    ['is nativpost worth it', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost brand voice', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost instagram tool', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost linkedin tool', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost tiktok', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost africa', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost nigeria', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost video tool', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost anti-slop', 'NativPost Brand', 0, 10, 'informational'],

    // ── 17. SOCIAL MEDIA ANALYTICS ────────────────────────────────────────────
    ['social media analytics tool', 'Analytics', 5200, 62, 'commercial'],
    ['social media performance tracker', 'Analytics', 2800, 50, 'commercial'],
    ['instagram analytics tool', 'Analytics', 4100, 57, 'commercial'],
    ['linkedin analytics dashboard', 'Analytics', 2400, 48, 'commercial'],
    ['social media reporting tool', 'Analytics', 3100, 52, 'commercial'],
    ['engagement rate tracker social media', 'Analytics', 1900, 43, 'commercial'],
    ['all in one social media analytics', 'Analytics', 1600, 40, 'commercial'],
    ['best social media analytics 2026', 'Analytics', 2200, 46, 'commercial'],
    ['track social media reach and impressions', 'Analytics', 1400, 38, 'commercial'],
    ['social media roi tracker', 'Analytics', 1700, 41, 'commercial'],
    ['ai social media performance insights', 'Analytics', 900, 32, 'commercial'],
    ['monitor social media growth', 'Analytics', 1200, 36, 'commercial'],
    ['unified social media dashboard', 'Analytics', 1100, 35, 'commercial'],
    ['tiktok analytics tool for brands', 'Analytics', 1800, 42, 'commercial'],
    ['instagram engagement tracker', 'Analytics', 2600, 49, 'commercial'],

    // ── 18. CONTENT STRATEGY ──────────────────────────────────────────────────
    ['social media content strategy', 'Content Strategy', 7200, 65, 'informational'],
    ['social media content strategy template', 'Content Strategy', 4800, 58, 'informational'],
    ['content strategy for brands', 'Content Strategy', 3400, 52, 'informational'],
    ['ai content strategy tool', 'Content Strategy', 2100, 45, 'commercial'],
    ['social media content pillars', 'Content Strategy', 2800, 48, 'informational'],
    ['content mix for social media', 'Content Strategy', 1600, 38, 'informational'],
    ['social media posting frequency guide', 'Content Strategy', 2200, 42, 'informational'],
    ['best content types for instagram', 'Content Strategy', 3100, 50, 'informational'],
    ['best content types for linkedin', 'Content Strategy', 2700, 46, 'informational'],
    ['what to post on social media for business', 'Content Strategy', 4200, 55, 'informational'],
    ['evergreen content social media', 'Content Strategy', 1900, 40, 'informational'],
    ['content repurposing strategy', 'Content Strategy', 2400, 44, 'informational'],
    ['social media topics for brands', 'Content Strategy', 1500, 37, 'informational'],
    ['b2b social media content strategy', 'Content Strategy', 2100, 42, 'informational'],
    ['social media content ideas ecommerce', 'Content Strategy', 1800, 40, 'mixed'],
    ['ai content strategy planning tool', 'Content Strategy', 1100, 33, 'commercial'],
    ['social media content calendar planning', 'Content Strategy', 2600, 47, 'informational'],
    ['how often to post social media business', 'Content Strategy', 3600, 52, 'informational'],
    ['social media content audit', 'Content Strategy', 1700, 38, 'informational'],
    ['content marketing for startups', 'Content Strategy', 2900, 49, 'informational'],

    // ── 19. TWITTER / X CONTENT ───────────────────────────────────────────────
    ['twitter post generator ai', 'Twitter/X Content', 3800, 54, 'commercial'],
    ['ai tweet generator', 'Twitter/X Content', 4600, 58, 'commercial'],
    ['x post generator ai', 'Twitter/X Content', 2400, 48, 'commercial'],
    ['ai write tweets for business', 'Twitter/X Content', 1900, 43, 'commercial'],
    ['twitter thread generator ai', 'Twitter/X Content', 2800, 50, 'commercial'],
    ['schedule tweets automatically', 'Twitter/X Content', 2200, 46, 'commercial'],
    ['best ai tool for twitter x 2026', 'Twitter/X Content', 1600, 40, 'commercial'],
    ['ai twitter marketing tool', 'Twitter/X Content', 1300, 37, 'commercial'],
    ['auto generate tweets', 'Twitter/X Content', 1700, 41, 'commercial'],
    ['twitter x content strategy', 'Twitter/X Content', 1400, 38, 'informational'],
    ['ai write x threads', 'Twitter/X Content', 1100, 35, 'commercial'],
    ['business twitter scheduler', 'Twitter/X Content', 900, 32, 'commercial'],
    ['twitter caption generator free', 'Twitter/X Content', 2100, 45, 'commercial'],
    ['how to grow on twitter x', 'Twitter/X Content', 3200, 51, 'informational'],
    ['twitter x post ideas for brands', 'Twitter/X Content', 1200, 36, 'mixed'],

    // ── 20a. THREADS & PINTEREST CONTENT ─────────────────────────────────────
    ['threads post generator ai', 'Threads & Pinterest', 1800, 35, 'commercial'],
    ['ai write threads posts', 'Threads & Pinterest', 1400, 32, 'commercial'],
    ['best threads content tool', 'Threads & Pinterest', 1100, 30, 'commercial'],
    ['threads scheduling tool', 'Threads & Pinterest', 900, 28, 'commercial'],
    ['threads caption generator', 'Threads & Pinterest', 1300, 31, 'commercial'],
    ['ai threads social media', 'Threads & Pinterest', 750, 26, 'commercial'],
    ['pinterest post generator ai', 'Threads & Pinterest', 2100, 42, 'commercial'],
    ['ai create pinterest pins', 'Threads & Pinterest', 1600, 38, 'commercial'],
    ['pinterest content strategy ai', 'Threads & Pinterest', 1200, 34, 'informational'],
    ['schedule pinterest posts ai', 'Threads & Pinterest', 1000, 32, 'commercial'],
    ['ai pinterest caption generator', 'Threads & Pinterest', 1400, 36, 'commercial'],
    ['pinterest marketing tool ai', 'Threads & Pinterest', 1100, 33, 'commercial'],
    ['ai generate pinterest descriptions', 'Threads & Pinterest', 900, 30, 'commercial'],
    ['best pinterest scheduler 2026', 'Threads & Pinterest', 1800, 40, 'commercial'],
    ['pinterest seo description generator', 'Threads & Pinterest', 1500, 37, 'commercial'],

    // ── 20b. YOUTUBE CONTENT ──────────────────────────────────────────────────
    ['youtube description generator ai', 'YouTube Content', 4800, 58, 'commercial'],
    ['ai youtube title generator', 'YouTube Content', 3900, 55, 'commercial'],
    ['youtube content ideas ai', 'YouTube Content', 2800, 50, 'mixed'],
    ['ai write youtube scripts', 'YouTube Content', 2200, 46, 'commercial'],
    ['youtube shorts caption generator ai', 'YouTube Content', 2600, 48, 'commercial'],
    ['schedule youtube videos automatically', 'YouTube Content', 1900, 43, 'commercial'],
    ['ai youtube seo tool', 'YouTube Content', 2400, 47, 'commercial'],
    ['ai generate youtube captions', 'YouTube Content', 1700, 41, 'commercial'],
    ['youtube channel content strategy ai', 'YouTube Content', 1400, 38, 'informational'],
    ['ai write youtube video description', 'YouTube Content', 3200, 52, 'commercial'],
    ['best youtube content tool ai 2026', 'YouTube Content', 1600, 39, 'commercial'],
    ['youtube shorts ideas generator', 'YouTube Content', 2100, 44, 'mixed'],
    ['ai create youtube thumbnail idea', 'YouTube Content', 1300, 36, 'commercial'],
    ['youtube script generator free ai', 'YouTube Content', 2900, 51, 'commercial'],
    ['auto schedule youtube posts', 'YouTube Content', 1100, 34, 'commercial'],

    // ── 20c. E-COMMERCE SOCIAL MEDIA ─────────────────────────────────────────
    ['social media tool for ecommerce', 'E-Commerce Social', 2400, 46, 'commercial'],
    ['ai captions for product posts', 'E-Commerce Social', 1900, 41, 'commercial'],
    ['ecommerce social media content generator', 'E-Commerce Social', 1600, 38, 'commercial'],
    ['ai write product descriptions social media', 'E-Commerce Social', 1400, 36, 'commercial'],
    ['shopify social media tool ai', 'E-Commerce Social', 1200, 34, 'commercial'],
    ['woocommerce social media ai', 'E-Commerce Social', 900, 30, 'commercial'],
    ['ai product launch social media', 'E-Commerce Social', 1100, 33, 'commercial'],
    ['ecommerce brand social media automation', 'E-Commerce Social', 800, 29, 'commercial'],
    ['instagram shop content ai', 'E-Commerce Social', 1500, 37, 'commercial'],
    ['social media for online store', 'E-Commerce Social', 2100, 43, 'commercial'],
    ['ai content for product promotions', 'E-Commerce Social', 1300, 35, 'commercial'],
    ['flash sale social media post generator', 'E-Commerce Social', 700, 27, 'commercial'],
    ['ecommerce instagram ai content', 'E-Commerce Social', 1000, 32, 'commercial'],
    ['best social media tool for shopify store', 'E-Commerce Social', 1700, 39, 'commercial'],
    ['ai generate posts for new product launch', 'E-Commerce Social', 850, 30, 'commercial'],

    // ── 20d. PROFESSIONAL SERVICES SOCIAL MEDIA ───────────────────────────────
    ['social media for law firm', 'Professional Services Social', 1400, 32, 'commercial'],
    ['social media for accountants', 'Professional Services Social', 1200, 30, 'commercial'],
    ['social media for consultants ai', 'Professional Services Social', 1600, 35, 'commercial'],
    ['social media for coaches ai', 'Professional Services Social', 1900, 37, 'commercial'],
    ['ai social media for real estate', 'Professional Services Social', 2200, 40, 'commercial'],
    ['social media for financial advisors', 'Professional Services Social', 1500, 33, 'commercial'],
    ['ai content for healthcare social media', 'Professional Services Social', 1300, 31, 'commercial'],
    ['social media for dentists ai', 'Professional Services Social', 1100, 29, 'commercial'],
    ['professional services social media tool', 'Professional Services Social', 900, 28, 'commercial'],
    ['b2b social media ai tool', 'Professional Services Social', 2600, 46, 'commercial'],
    ['thought leadership content ai', 'Professional Services Social', 1700, 36, 'commercial'],
    ['ai social media for service businesses', 'Professional Services Social', 1100, 30, 'commercial'],
    ['social media ideas for service industry', 'Professional Services Social', 1400, 32, 'informational'],
    ['ai write professional social media posts', 'Professional Services Social', 1000, 29, 'commercial'],
    ['linkedin content for consultants ai', 'Professional Services Social', 800, 27, 'commercial'],

    // ── 20e. RESTAURANT & FOOD SOCIAL MEDIA ──────────────────────────────────
    ['social media for restaurants ai', 'Restaurant & Food Social', 2100, 38, 'commercial'],
    ['restaurant caption generator ai', 'Restaurant & Food Social', 1800, 35, 'commercial'],
    ['food business social media tool', 'Restaurant & Food Social', 1600, 33, 'commercial'],
    ['ai write food captions', 'Restaurant & Food Social', 1400, 31, 'commercial'],
    ['restaurant instagram content ai', 'Restaurant & Food Social', 1200, 30, 'commercial'],
    ['food brand social media automation', 'Restaurant & Food Social', 900, 27, 'commercial'],
    ['cafe social media content ai', 'Restaurant & Food Social', 800, 26, 'commercial'],
    ['menu post generator ai', 'Restaurant & Food Social', 700, 25, 'commercial'],
    ['food truck social media tool', 'Restaurant & Food Social', 600, 24, 'commercial'],
    ['bakery instagram content ai', 'Restaurant & Food Social', 550, 23, 'commercial'],

    // ── 20f. TEAM COLLABORATION FEATURES ─────────────────────────────────────
    ['team social media management tool', 'Team Collaboration', 2200, 44, 'commercial'],
    ['social media approval workflow tool', 'Team Collaboration', 1600, 38, 'commercial'],
    ['collaborate on social media content', 'Team Collaboration', 1300, 35, 'commercial'],
    ['social media content review tool', 'Team Collaboration', 1100, 33, 'commercial'],
    ['team social media approval app', 'Team Collaboration', 900, 30, 'commercial'],
    ['multi user social media tool', 'Team Collaboration', 800, 29, 'commercial'],
    ['social media manager tool teams', 'Team Collaboration', 1800, 41, 'commercial'],
    ['assign social media tasks to team', 'Team Collaboration', 700, 27, 'commercial'],
    ['social media content feedback tool', 'Team Collaboration', 600, 25, 'commercial'],
    ['team workflow social media content', 'Team Collaboration', 550, 24, 'commercial'],
    ['social media tool with roles', 'Team Collaboration', 500, 23, 'commercial'],
    ['content approval before publishing', 'Team Collaboration', 480, 22, 'commercial'],
    ['team social media calendar', 'Team Collaboration', 1400, 36, 'commercial'],
    ['client content approval tool', 'Team Collaboration', 1200, 33, 'commercial'],
    ['social media team dashboard', 'Team Collaboration', 1000, 31, 'commercial'],

    // ── 20g. AI WRITING / COPYWRITING ────────────────────────────────────────
    ['ai copywriter social media', 'AI Writing', 2800, 50, 'commercial'],
    ['ai write marketing copy', 'AI Writing', 3400, 54, 'commercial'],
    ['ai caption writer', 'AI Writing', 4200, 57, 'commercial'],
    ['ai content writer for brands', 'AI Writing', 2600, 49, 'commercial'],
    ['ai marketing copywriter', 'AI Writing', 3100, 52, 'commercial'],
    ['ai write brand content', 'AI Writing', 2000, 43, 'commercial'],
    ['ai generate marketing copy', 'AI Writing', 1800, 41, 'commercial'],
    ['ai write engaging posts', 'AI Writing', 1600, 39, 'commercial'],
    ['ai content that converts', 'AI Writing', 1400, 37, 'commercial'],
    ['ai social media copy generator', 'AI Writing', 1200, 35, 'commercial'],
    ['ai write persuasive social media', 'AI Writing', 1000, 33, 'commercial'],
    ['ai write call to action social media', 'AI Writing', 900, 31, 'commercial'],
    ['ai write hooks for social media', 'AI Writing', 2200, 45, 'commercial'],
    ['ai hook generator social media', 'AI Writing', 1900, 42, 'commercial'],
    ['ai write controversial posts', 'AI Writing', 800, 29, 'commercial'],
    ['ai controversial social media content', 'AI Writing', 700, 27, 'commercial'],
    ['ai write thought-provoking posts', 'AI Writing', 600, 25, 'commercial'],
    ['ai write concise social media posts', 'AI Writing', 550, 24, 'commercial'],
    ['ai social media copywriting tool', 'AI Writing', 1500, 38, 'commercial'],
    ['content creation ai that sounds human', 'AI Writing', 2100, 44, 'commercial'],

    // ── 20h. MEDIA LIBRARY / ASSET MANAGEMENT ────────────────────────────────
    ['social media asset manager', 'Media Library', 1600, 36, 'commercial'],
    ['brand asset management social media', 'Media Library', 1300, 33, 'commercial'],
    ['media library for social media', 'Media Library', 900, 29, 'commercial'],
    ['social media image library tool', 'Media Library', 800, 28, 'commercial'],
    ['manage brand assets social media', 'Media Library', 700, 26, 'commercial'],
    ['social media graphic library', 'Media Library', 600, 24, 'commercial'],
    ['store brand images for social media', 'Media Library', 550, 23, 'commercial'],
    ['reuse content social media tool', 'Media Library', 500, 22, 'commercial'],
    ['brand content storage tool', 'Media Library', 480, 21, 'commercial'],
    ['ai created assets social media library', 'Media Library', 420, 20, 'commercial'],

    // ── 20i. CONTENT MODES & STYLES ───────────────────────────────────────────
    ['controversial social media posts ai', 'Content Modes', 1800, 38, 'commercial'],
    ['ai generate controversy posts', 'Content Modes', 900, 29, 'commercial'],
    ['concise social media posts ai', 'Content Modes', 800, 28, 'commercial'],
    ['short social media captions ai', 'Content Modes', 2400, 46, 'commercial'],
    ['punchy social media captions tool', 'Content Modes', 700, 26, 'commercial'],
    ['three versions of social media post', 'Content Modes', 600, 24, 'commercial'],
    ['multiple variations social media ai', 'Content Modes', 550, 23, 'commercial'],
    ['ai generate post variants', 'Content Modes', 500, 22, 'commercial'],
    ['different takes same social media topic', 'Content Modes', 450, 21, 'informational'],
    ['ai social media content modes', 'Content Modes', 400, 20, 'commercial'],

    // ── 20j. MARKETING AUTOMATION ────────────────────────────────────────────
    ['social media marketing automation', 'Marketing Automation', 4400, 58, 'commercial'],
    ['automate social media marketing', 'Marketing Automation', 3600, 54, 'commercial'],
    ['marketing automation tool small business', 'Marketing Automation', 2800, 50, 'commercial'],
    ['social media automation for brands', 'Marketing Automation', 2200, 46, 'commercial'],
    ['best marketing automation 2026 social', 'Marketing Automation', 1800, 42, 'commercial'],
    ['set and forget social media tool', 'Marketing Automation', 1400, 37, 'commercial'],
    ['autopilot social media marketing', 'Marketing Automation', 1100, 34, 'commercial'],
    ['automate content creation and posting', 'Marketing Automation', 900, 30, 'commercial'],
    ['hands off social media management', 'Marketing Automation', 700, 27, 'commercial'],
    ['run social media on autopilot', 'Marketing Automation', 600, 25, 'commercial'],
    ['ai social media pilot', 'Marketing Automation', 550, 23, 'commercial'],
    ['schedule and forget social media', 'Marketing Automation', 500, 22, 'commercial'],
    ['social media without daily effort', 'Marketing Automation', 480, 21, 'commercial'],
    ['ai automate instagram posts', 'Marketing Automation', 1600, 39, 'commercial'],
    ['marketing automation with ai content', 'Marketing Automation', 1300, 36, 'commercial'],

    // ── 20k. NICHE / LONG-TAIL OPPORTUNITIES ──────────────────────────────────
    ['best social media tool for coaches', 'Niche Long Tail', 900, 25, 'commercial'],
    ['social media tool for personal brands', 'Niche Long Tail', 1800, 35, 'commercial'],
    ['ai tool for influencers', 'Niche Long Tail', 2400, 42, 'commercial'],
    ['content creator tool ai', 'Niche Long Tail', 3100, 50, 'commercial'],
    ['social media tool for nonprofits', 'Niche Long Tail', 800, 22, 'commercial'],
    ['social media tool for fitness brands', 'Niche Long Tail', 700, 21, 'commercial'],
    ['social media for fashion brands ai', 'Niche Long Tail', 1200, 28, 'commercial'],
    ['ai captions for clothing brands', 'Niche Long Tail', 600, 20, 'commercial'],
    ['social media for beauty brands ai', 'Niche Long Tail', 1400, 30, 'commercial'],
    ['ai social media for beauty salon', 'Niche Long Tail', 550, 19, 'commercial'],
    ['social media for event planners', 'Niche Long Tail', 700, 21, 'commercial'],
    ['ai content for travel brands', 'Niche Long Tail', 1100, 27, 'commercial'],
    ['social media tool for photographers', 'Niche Long Tail', 900, 24, 'commercial'],
    ['social media for hotels ai', 'Niche Long Tail', 800, 22, 'commercial'],
    ['ai content for tech startups', 'Niche Long Tail', 1500, 32, 'commercial'],
    ['social media tool for saas companies', 'Niche Long Tail', 1300, 30, 'commercial'],
    ['ai write saas social media content', 'Niche Long Tail', 700, 21, 'commercial'],
    ['social media for crypto brands', 'Niche Long Tail', 1600, 33, 'commercial'],
    ['content tool for fintech social media', 'Niche Long Tail', 900, 25, 'commercial'],
    ['social media for logistics companies', 'Niche Long Tail', 600, 19, 'commercial'],

    // ── 20l. KEYWORD RESEARCH & SEO TERMS ────────────────────────────────────
    ['social media seo tool', 'SEO & Discovery', 1800, 38, 'commercial'],
    ['hashtag research tool', 'SEO & Discovery', 2600, 46, 'commercial'],
    ['best hashtag generator 2026', 'SEO & Discovery', 3100, 50, 'commercial'],
    ['ai hashtag generator', 'SEO & Discovery', 4200, 56, 'commercial'],
    ['hashtag strategy tool', 'SEO & Discovery', 1600, 36, 'commercial'],
    ['trending hashtags generator ai', 'SEO & Discovery', 2400, 44, 'commercial'],
    ['instagram hashtag finder ai', 'SEO & Discovery', 3200, 52, 'commercial'],
    ['linkedin hashtag generator', 'SEO & Discovery', 1400, 34, 'commercial'],
    ['tiktok hashtag generator', 'SEO & Discovery', 3600, 54, 'commercial'],
    ['best hashtags for instagram business', 'SEO & Discovery', 2800, 48, 'informational'],
    ['social media keyword research', 'SEO & Discovery', 1200, 32, 'informational'],
    ['ai find trending topics social media', 'SEO & Discovery', 900, 28, 'commercial'],
    ['social media trend tool', 'SEO & Discovery', 1400, 34, 'commercial'],
    ['what is trending on instagram ai', 'SEO & Discovery', 1100, 30, 'mixed'],
    ['ai content ideas from trending topics', 'SEO & Discovery', 800, 27, 'commercial'],

    // ── 20m. LANGUAGE / FRENCH MARKET ────────────────────────────────────────
    ['outil gestion reseaux sociaux ia', 'French Market', 1200, 22, 'commercial'],
    ['generateur de contenu reseaux sociaux', 'French Market', 900, 20, 'commercial'],
    ['ia creation contenu instagram', 'French Market', 800, 19, 'commercial'],
    ['outil ia reseaux sociaux', 'French Market', 700, 18, 'commercial'],
    ['generateur ia post linkedin', 'French Market', 600, 17, 'commercial'],
    ['outil planification reseaux sociaux ia', 'French Market', 550, 16, 'commercial'],
    ['ia marque voix reseaux sociaux', 'French Market', 400, 14, 'commercial'],
    ['creer contenu reseaux sociaux automatiquement', 'French Market', 750, 18, 'commercial'],
    ['meilleur outil ia reseaux sociaux', 'French Market', 650, 17, 'commercial'],
    ['ia post instagram automatique', 'French Market', 580, 16, 'commercial'],
    ['outil ia marketing reseaux sociaux', 'French Market', 500, 15, 'commercial'],
    ['generateur ia pour facebook', 'French Market', 450, 14, 'commercial'],
    ['planification ia reseaux sociaux afrique', 'French Market', 380, 12, 'commercial'],
    ['contenu reseaux sociaux ia francophone', 'French Market', 320, 11, 'commercial'],
    ['nativpost francais', 'French Market', 0, 10, 'commercial'],

    // ── 20n. COMPETITOR FEATURE COMPARISONS ───────────────────────────────────
    ['does buffer have ai content generation', 'Competitor Feature Comparison', 800, 20, 'informational'],
    ['does hootsuite use ai to write posts', 'Competitor Feature Comparison', 700, 19, 'informational'],
    ['ocoya vs nativpost features', 'Competitor Feature Comparison', 400, 15, 'informational'],
    ['buffer ai vs nativpost', 'Competitor Feature Comparison', 350, 14, 'informational'],
    ['does predis have brand voice', 'Competitor Feature Comparison', 450, 15, 'informational'],
    ['social media tool with better brand voice than jasper', 'Competitor Feature Comparison', 300, 13, 'commercial'],
    ['which social media tool has best ai', 'Competitor Feature Comparison', 900, 22, 'informational'],
    ['social media tool that filters ai content', 'Competitor Feature Comparison', 400, 15, 'commercial'],
    ['hootsuite vs nativpost', 'Competitor Feature Comparison', 350, 14, 'commercial'],
    ['later vs nativpost', 'Competitor Feature Comparison', 280, 12, 'commercial'],
    ['does ocoya filter generic ai content', 'Competitor Feature Comparison', 250, 12, 'informational'],
    ['best brand voice social media tool 2026', 'Competitor Feature Comparison', 600, 18, 'commercial'],
    ['which ai social media has video generation', 'Competitor Feature Comparison', 500, 16, 'commercial'],
    ['social media tool with ugc ad creator', 'Competitor Feature Comparison', 350, 14, 'commercial'],
    ['ai tool that learns brand voice over time', 'Competitor Feature Comparison', 600, 18, 'commercial'],

    // ── 20o. CASE STUDIES & SOCIAL PROOF ─────────────────────────────────────
    ['how brands use ai social media', 'Social Proof', 2200, 38, 'informational'],
    ['ai social media success stories', 'Social Proof', 1400, 32, 'informational'],
    ['case study ai social media growth', 'Social Proof', 900, 27, 'informational'],
    ['small business ai social media results', 'Social Proof', 700, 24, 'informational'],
    ['ai social media roi case study', 'Social Proof', 800, 25, 'informational'],
    ['brands using ai for social media 2026', 'Social Proof', 1600, 35, 'informational'],
    ['ai content marketing results', 'Social Proof', 1100, 29, 'informational'],
    ['social media growth with ai tool', 'Social Proof', 600, 22, 'informational'],
    ['does ai social media actually work', 'Social Proof', 1900, 37, 'informational'],
    ['ai social media testimonials', 'Social Proof', 400, 16, 'informational'],

    // ── 20p. CONTENT REPURPOSING ──────────────────────────────────────────────
    ['repurpose content for social media ai', 'Content Repurposing', 2100, 40, 'commercial'],
    ['ai repurpose blog post for social media', 'Content Repurposing', 1800, 38, 'commercial'],
    ['turn blog into social media posts ai', 'Content Repurposing', 1500, 36, 'commercial'],
    ['repurpose youtube video to instagram ai', 'Content Repurposing', 1200, 33, 'commercial'],
    ['content repurposing tool ai', 'Content Repurposing', 1600, 37, 'commercial'],
    ['ai turn long content into social posts', 'Content Repurposing', 900, 29, 'commercial'],
    ['repurpose podcast to social media', 'Content Repurposing', 1100, 31, 'commercial'],
    ['ai summarize content for social media', 'Content Repurposing', 800, 27, 'commercial'],
    ['content atomization tool ai', 'Content Repurposing', 700, 25, 'commercial'],
    ['ai clip blog to captions', 'Content Repurposing', 600, 23, 'commercial'],

    // ── 20q. GENERAL MARKETING & GROWTH ──────────────────────────────────────
    ['digital marketing tool for small business', 'General Marketing', 4200, 57, 'commercial'],
    ['ai marketing tool 2026', 'General Marketing', 3100, 52, 'commercial'],
    ['best ai marketing software', 'General Marketing', 2800, 50, 'commercial'],
    ['grow brand on social media', 'General Marketing', 3600, 53, 'informational'],
    ['increase social media engagement', 'General Marketing', 4800, 59, 'informational'],
    ['social media growth tool', 'General Marketing', 2400, 47, 'commercial'],
    ['content marketing platform', 'General Marketing', 2200, 45, 'commercial'],
    ['ai marketing software 2026', 'General Marketing', 2600, 48, 'commercial'],
    ['online marketing tool for brands', 'General Marketing', 1800, 41, 'commercial'],
    ['boost social media presence ai', 'General Marketing', 1400, 37, 'commercial'],
    ['improve social media reach tool', 'General Marketing', 1100, 33, 'commercial'],
    ['social media visibility tool', 'General Marketing', 900, 30, 'commercial'],
    ['get more engagement social media', 'General Marketing', 3900, 54, 'informational'],
    ['build social media presence ai', 'General Marketing', 1600, 38, 'commercial'],
    ['ai grow social media following', 'General Marketing', 1300, 35, 'commercial'],
    ['social media tool increase followers', 'General Marketing', 1700, 39, 'commercial'],
    ['social media marketing platform 2026', 'General Marketing', 3200, 52, 'commercial'],
    ['all in one marketing platform ai', 'General Marketing', 2100, 44, 'commercial'],
    ['best marketing tools for brands 2026', 'General Marketing', 1900, 42, 'informational'],
    ['ai tools for brand growth', 'General Marketing', 1500, 37, 'commercial'],

    // ── 20r. HEALTH / WELLNESS BRANDS ────────────────────────────────────────
    ['social media tool for wellness brands', 'Health & Wellness Social', 800, 22, 'commercial'],
    ['ai captions for fitness content', 'Health & Wellness Social', 1200, 28, 'commercial'],
    ['gym social media content ai', 'Health & Wellness Social', 900, 25, 'commercial'],
    ['wellness brand instagram tool ai', 'Health & Wellness Social', 700, 21, 'commercial'],
    ['health brand social media ai', 'Health & Wellness Social', 650, 21, 'commercial'],
    ['yoga studio social media ai', 'Health & Wellness Social', 600, 20, 'commercial'],
    ['nutrition brand social media tool', 'Health & Wellness Social', 550, 19, 'commercial'],
    ['personal trainer social media ai', 'Health & Wellness Social', 1100, 27, 'commercial'],
    ['fitness influencer content ai', 'Health & Wellness Social', 900, 25, 'commercial'],
    ['mental health brand social media ai', 'Health & Wellness Social', 700, 21, 'commercial'],

    // ── 20s. TECH / SAAS COMPANY CONTENT ──────────────────────────────────────
    ['saas company social media tool', 'SaaS & Tech Social', 1300, 30, 'commercial'],
    ['ai social media for software companies', 'SaaS & Tech Social', 900, 26, 'commercial'],
    ['tech startup social media ai', 'SaaS & Tech Social', 1100, 28, 'commercial'],
    ['social media tool for apps', 'SaaS & Tech Social', 800, 24, 'commercial'],
    ['product launch social media ai tool', 'SaaS & Tech Social', 1600, 33, 'commercial'],
    ['ai write product announcement post', 'SaaS & Tech Social', 1400, 31, 'commercial'],
    ['saas marketing social media ai', 'SaaS & Tech Social', 1000, 27, 'commercial'],
    ['developer tool marketing ai', 'SaaS & Tech Social', 700, 22, 'commercial'],
    ['b2b saas social media content', 'SaaS & Tech Social', 1200, 29, 'informational'],
    ['software company instagram linkedin ai', 'SaaS & Tech Social', 600, 20, 'commercial'],

    // ── 20t. INTERNATIONAL / LANGUAGE-SPECIFIC ────────────────────────────────
    ['social media tool for international brands', 'International', 900, 24, 'commercial'],
    ['multilingual social media ai', 'International', 1100, 28, 'commercial'],
    ['ai social media english and french', 'International', 600, 19, 'commercial'],
    ['global social media management ai', 'International', 800, 23, 'commercial'],
    ['social media tool west africa', 'International', 500, 15, 'commercial'],
    ['social media tool east africa', 'International', 450, 14, 'commercial'],
    ['social media management francophone africa', 'International', 400, 13, 'commercial'],
    ['ai social media tool nigeria ghana kenya', 'International', 550, 16, 'commercial'],
    ['best social media tool developing markets', 'International', 700, 20, 'commercial'],
    ['social media tool affordable africa', 'International', 600, 17, 'commercial'],

    // ── 20. PRICING / TRIAL / REVIEWS ────────────────────────────────────────
    ['best ai social media tool under 50', 'Pricing & Reviews', 1800, 38, 'commercial'],
    ['cheapest ai social media tool', 'Pricing & Reviews', 2100, 42, 'commercial'],
    ['social media tool free trial', 'Pricing & Reviews', 3200, 52, 'commercial'],
    ['ai social media pricing comparison', 'Pricing & Reviews', 1400, 36, 'commercial'],
    ['social media tool 19 dollars month', 'Pricing & Reviews', 600, 22, 'commercial'],
    ['best value social media tool 2026', 'Pricing & Reviews', 1900, 40, 'commercial'],
    ['social media tool monthly subscription', 'Pricing & Reviews', 1100, 33, 'commercial'],
    ['ai social media tool reviews 2026', 'Pricing & Reviews', 1600, 38, 'informational'],
    ['is ai social media worth it', 'Pricing & Reviews', 2400, 44, 'informational'],
    ['social media tool comparison 2026', 'Pricing & Reviews', 2800, 48, 'informational'],
    ['best cheap social media scheduler', 'Pricing & Reviews', 1700, 39, 'commercial'],
    ['social media tool no annual contract', 'Pricing & Reviews', 900, 30, 'commercial'],
    ['affordable ai social media platform', 'Pricing & Reviews', 1300, 35, 'commercial'],
    ['social media tool for 20 a month', 'Pricing & Reviews', 750, 28, 'commercial'],
    ['top rated social media tools 2026', 'Pricing & Reviews', 2200, 43, 'informational'],
    ['honest review ai social media tool', 'Pricing & Reviews', 800, 28, 'informational'],
    ['ai social media tool that actually works', 'Pricing & Reviews', 1100, 32, 'commercial'],
    ['try ai social media tool free', 'Pricing & Reviews', 1400, 36, 'commercial'],
    ['social media tool trial no credit card', 'Pricing & Reviews', 1900, 40, 'commercial'],
    ['social media tool 7 day trial', 'Pricing & Reviews', 1100, 33, 'commercial'],

    // ── 21. CONTENT CREATION WORKFLOW ────────────────────────────────────────
    ['content creation workflow tool', 'Workflow', 2100, 40, 'commercial'],
    ['social media content workflow', 'Workflow', 1600, 36, 'commercial'],
    ['ai content workflow for brands', 'Workflow', 1200, 32, 'commercial'],
    ['automate content creation workflow', 'Workflow', 900, 28, 'commercial'],
    ['content production tool for social media', 'Workflow', 800, 27, 'commercial'],
    ['social media content system', 'Workflow', 750, 26, 'commercial'],
    ['ai content pipeline social media', 'Workflow', 600, 23, 'commercial'],
    ['batch create social media content', 'Workflow', 1400, 34, 'commercial'],
    ['plan social media content in advance', 'Workflow', 2200, 42, 'informational'],
    ['create month of social media content ai', 'Workflow', 1100, 30, 'commercial'],
    ['weekly social media content planner ai', 'Workflow', 900, 28, 'commercial'],
    ['social media content plan template ai', 'Workflow', 1700, 37, 'commercial'],
    ['one click social media publishing', 'Workflow', 600, 22, 'commercial'],
    ['save time creating social media content', 'Workflow', 2600, 46, 'informational'],
    ['how long does social media content take', 'Workflow', 1800, 35, 'informational'],
    ['ai reduce social media time', 'Workflow', 800, 26, 'informational'],
    ['time saving social media ai', 'Workflow', 700, 25, 'commercial'],
    ['stop wasting time on social media', 'Workflow', 1200, 30, 'informational'],
    ['social media in less time ai', 'Workflow', 550, 22, 'commercial'],
    ['hours saved social media ai', 'Workflow', 480, 21, 'commercial'],

    // ── 22. INSTAGRAM GROWTH ORGANIC ─────────────────────────────────────────
    ['how to grow instagram organically', 'Instagram Growth', 6400, 62, 'informational'],
    ['instagram growth strategy 2026', 'Instagram Growth', 4200, 55, 'informational'],
    ['increase instagram reach', 'Instagram Growth', 3800, 53, 'informational'],
    ['instagram engagement tips 2026', 'Instagram Growth', 3100, 50, 'informational'],
    ['best time to post instagram', 'Instagram Growth', 5200, 60, 'informational'],
    ['instagram algorithm 2026', 'Instagram Growth', 4800, 58, 'informational'],
    ['how to get instagram followers fast', 'Instagram Growth', 5600, 62, 'informational'],
    ['instagram content ideas business', 'Instagram Growth', 3400, 52, 'informational'],
    ['instagram marketing tips for small business', 'Instagram Growth', 2800, 48, 'informational'],
    ['best instagram posting frequency', 'Instagram Growth', 2200, 44, 'informational'],
    ['instagram reach drop fix', 'Instagram Growth', 1800, 38, 'informational'],
    ['how to get more instagram likes', 'Instagram Growth', 4100, 55, 'informational'],
    ['instagram for business tips 2026', 'Instagram Growth', 3200, 51, 'informational'],
    ['reels vs posts instagram 2026', 'Instagram Growth', 2600, 46, 'informational'],
    ['how to write instagram captions that get engagement', 'Instagram Growth', 2100, 42, 'informational'],

    // ── 23. LINKEDIN GROWTH ────────────────────────────────────────────────────
    ['how to grow linkedin following', 'LinkedIn Growth', 4800, 55, 'informational'],
    ['linkedin growth strategy 2026', 'LinkedIn Growth', 3200, 50, 'informational'],
    ['linkedin tips for small business', 'LinkedIn Growth', 2800, 47, 'informational'],
    ['best time to post on linkedin', 'LinkedIn Growth', 3600, 52, 'informational'],
    ['linkedin algorithm 2026', 'LinkedIn Growth', 2400, 45, 'informational'],
    ['how to get linkedin connections', 'LinkedIn Growth', 3100, 49, 'informational'],
    ['linkedin post tips for engagement', 'LinkedIn Growth', 2200, 43, 'informational'],
    ['grow linkedin company page', 'LinkedIn Growth', 1800, 39, 'informational'],
    ['linkedin content strategy for founders', 'LinkedIn Growth', 1500, 36, 'informational'],
    ['linkedin marketing for b2b', 'LinkedIn Growth', 2600, 46, 'informational'],

    // ── 24. TIKTOK GROWTH ─────────────────────────────────────────────────────
    ['how to grow tiktok for business', 'TikTok Growth', 5200, 58, 'informational'],
    ['tiktok strategy for small business', 'TikTok Growth', 3400, 52, 'informational'],
    ['tiktok tips for brands 2026', 'TikTok Growth', 2800, 48, 'informational'],
    ['how to go viral on tiktok', 'TikTok Growth', 6800, 65, 'informational'],
    ['best time to post tiktok', 'TikTok Growth', 4200, 56, 'informational'],
    ['tiktok algorithm 2026', 'TikTok Growth', 3600, 53, 'informational'],
    ['tiktok content ideas for business', 'TikTok Growth', 2400, 46, 'informational'],
    ['how to get tiktok followers fast', 'TikTok Growth', 4800, 58, 'informational'],
    ['tiktok marketing for small business', 'TikTok Growth', 2200, 43, 'informational'],
    ['tiktok for brand awareness', 'TikTok Growth', 1800, 38, 'informational'],

    // ── 25. UGC & INFLUENCER MARKETING ────────────────────────────────────────
    ['ugc content creator tool', 'UGC & Influencer', 2100, 43, 'commercial'],
    ['what is ugc marketing', 'UGC & Influencer', 3400, 48, 'informational'],
    ['ugc ads best practices', 'UGC & Influencer', 1800, 38, 'informational'],
    ['ai ugc content generator', 'UGC & Influencer', 1500, 35, 'commercial'],
    ['how to create ugc style videos', 'UGC & Influencer', 2600, 46, 'informational'],
    ['ugc ad template generator', 'UGC & Influencer', 1200, 31, 'commercial'],
    ['ugc hook problem solution cta', 'UGC & Influencer', 900, 27, 'informational'],
    ['ai create ugc ads for brands', 'UGC & Influencer', 1100, 29, 'commercial'],
    ['ugc content for small business', 'UGC & Influencer', 800, 25, 'commercial'],
    ['best ugc ad generator 2026', 'UGC & Influencer', 700, 23, 'commercial'],

    // ── 26. SOCIAL MEDIA FOR AFRICA SPECIFICS ────────────────────────────────
    ['social media marketing for african brands', 'Africa Specifics', 900, 18, 'informational'],
    ['grow business on social media nigeria', 'Africa Specifics', 1400, 22, 'informational'],
    ['best social media platforms in nigeria', 'Africa Specifics', 1800, 24, 'informational'],
    ['social media tips for african business', 'Africa Specifics', 700, 17, 'informational'],
    ['instagram for business nigeria', 'Africa Specifics', 1200, 20, 'informational'],
    ['how to use instagram for business kenya', 'Africa Specifics', 1000, 18, 'informational'],
    ['linkedin for business south africa', 'Africa Specifics', 900, 18, 'informational'],
    ['tiktok for business ghana', 'Africa Specifics', 750, 16, 'informational'],
    ['social media for african startups', 'Africa Specifics', 600, 15, 'informational'],
    ['how to build a brand online in africa', 'Africa Specifics', 550, 14, 'informational'],
    ['nigerian sme digital marketing', 'Africa Specifics', 800, 17, 'informational'],
    ['digital marketing for kenya businesses', 'Africa Specifics', 700, 16, 'informational'],
    ['social media for south african brands', 'Africa Specifics', 850, 17, 'informational'],
    ['paystack payment social media tool', 'Africa Specifics', 500, 13, 'commercial'],
    ['africa social media automation tool', 'Africa Specifics', 480, 13, 'commercial'],

    // ── 27. SAAS PRICING PSYCHOLOGY ───────────────────────────────────────────
    ['social media tool 19 per month', 'SaaS Pricing', 600, 20, 'commercial'],
    ['social media tool 39 per month', 'SaaS Pricing', 500, 18, 'commercial'],
    ['social media tool starter plan', 'SaaS Pricing', 700, 21, 'commercial'],
    ['unlimited social media posts plan', 'SaaS Pricing', 800, 22, 'commercial'],
    ['social media tool growth plan', 'SaaS Pricing', 600, 20, 'commercial'],
    ['social media tool agency plan unlimited', 'SaaS Pricing', 700, 21, 'commercial'],
    ['best value social media tool per month', 'SaaS Pricing', 1200, 28, 'commercial'],
    ['social media tool no annual commitment', 'SaaS Pricing', 750, 22, 'commercial'],
    ['try before you pay social media tool', 'SaaS Pricing', 900, 24, 'commercial'],
    ['social media tool setup fee', 'SaaS Pricing', 400, 16, 'commercial'],

    // ── 28. SPECIFIC FEATURE SEARCHES ─────────────────────────────────────────
    ['ai that adapts per platform', 'Feature Search', 600, 22, 'commercial'],
    ['different captions per platform ai', 'Feature Search', 800, 25, 'commercial'],
    ['ai write linkedin different from instagram', 'Feature Search', 700, 23, 'commercial'],
    ['one tool post all social media platforms', 'Feature Search', 1600, 36, 'commercial'],
    ['social media tool connect instagram linkedin tiktok', 'Feature Search', 1400, 34, 'commercial'],
    ['topic memory social media ai', 'Feature Search', 400, 15, 'commercial'],
    ['ai that avoids repeating content', 'Feature Search', 550, 20, 'commercial'],
    ['ai social media feedback loop', 'Feature Search', 450, 17, 'commercial'],
    ['social media ai that improves over time', 'Feature Search', 600, 21, 'commercial'],
    ['ai social media platform with analytics', 'Feature Search', 1100, 30, 'commercial'],
    ['social media tool with image creation', 'Feature Search', 1300, 32, 'commercial'],
    ['social media tool video and captions', 'Feature Search', 1000, 29, 'commercial'],
    ['ai social media with team approval', 'Feature Search', 700, 23, 'commercial'],
    ['social media tool notification email', 'Feature Search', 500, 19, 'commercial'],
    ['ai social media brand-safe content', 'Feature Search', 600, 21, 'commercial'],

    // ── 29. BLOG CONTENT TO SUPPORT SEO ──────────────────────────────────────
    ['why ai social media content fails', 'SEO Blog Topics', 1400, 28, 'informational'],
    ['how to avoid generic ai captions', 'SEO Blog Topics', 1100, 25, 'informational'],
    ['ai social media vs human social media', 'SEO Blog Topics', 2200, 38, 'informational'],
    ['future of social media ai 2026', 'SEO Blog Topics', 2800, 44, 'informational'],
    ['is ai replacing social media managers', 'SEO Blog Topics', 3400, 49, 'informational'],
    ['ai social media marketing trends 2026', 'SEO Blog Topics', 3100, 47, 'informational'],
    ['how ai changes social media marketing', 'SEO Blog Topics', 2600, 43, 'informational'],
    ['best social media content types 2026', 'SEO Blog Topics', 2900, 45, 'informational'],
    ['video vs image social media 2026', 'SEO Blog Topics', 1800, 36, 'informational'],
    ['social media mistakes businesses make', 'SEO Blog Topics', 2200, 38, 'informational'],
    ['how much does social media management cost', 'SEO Blog Topics', 4800, 56, 'commercial'],
    ['hire social media manager or use ai', 'SEO Blog Topics', 1600, 33, 'informational'],
    ['social media agency vs ai tool', 'SEO Blog Topics', 1200, 29, 'informational'],
    ['cost of hiring social media manager', 'SEO Blog Topics', 2400, 42, 'informational'],
    ['ai social media roi calculator', 'SEO Blog Topics', 900, 25, 'informational'],

    // ── 30. FINAL BATCH — MIXED HIGH-OPPORTUNITY ─────────────────────────────
    ['ai brand content creator', 'Misc High Value', 1900, 40, 'commercial'],
    ['social media content machine', 'Misc High Value', 700, 24, 'commercial'],
    ['generate social media posts fast', 'Misc High Value', 1400, 34, 'commercial'],
    ['ai tool that generates posts daily', 'Misc High Value', 900, 28, 'commercial'],
    ['never run out of social media content', 'Misc High Value', 1100, 30, 'informational'],
    ['social media content ideas never repeat', 'Misc High Value', 600, 22, 'informational'],
    ['always have content to post social media', 'Misc High Value', 800, 25, 'informational'],
    ['ai generates social media posts for me', 'Misc High Value', 1600, 36, 'commercial'],
    ['let ai run my social media', 'Misc High Value', 1200, 31, 'commercial'],
    ['social media without stress ai', 'Misc High Value', 700, 24, 'commercial'],
    ['consistent posting social media ai', 'Misc High Value', 1300, 32, 'commercial'],
    ['stay consistent on social media ai', 'Misc High Value', 900, 28, 'commercial'],
    ['ai post every day social media', 'Misc High Value', 1100, 30, 'commercial'],
    ['never miss a post social media ai', 'Misc High Value', 500, 21, 'commercial'],
    ['social media presence without effort ai', 'Misc High Value', 600, 22, 'commercial'],
    ['ai write posts so i dont have to', 'Misc High Value', 1400, 34, 'commercial'],
    ['social media content on autopilot', 'Misc High Value', 1700, 37, 'commercial'],
    ['brand social media without agency', 'Misc High Value', 900, 28, 'commercial'],
    ['look like a social media pro with ai', 'Misc High Value', 700, 24, 'commercial'],
    ['professional social media without expert', 'Misc High Value', 600, 22, 'commercial'],
    ['compete with big brands social media ai', 'Misc High Value', 550, 21, 'commercial'],
    ['level up social media with ai', 'Misc High Value', 800, 26, 'commercial'],
    ['ai powered brand marketing', 'Misc High Value', 1200, 31, 'commercial'],
    ['smart brand content tool', 'Misc High Value', 700, 24, 'commercial'],
    ['ai tool that understands my brand', 'Misc High Value', 900, 28, 'commercial'],
    ['social media tool that grows with you', 'Misc High Value', 550, 21, 'commercial'],
    ['scalable social media management ai', 'Misc High Value', 700, 24, 'commercial'],
    ['social media for growing businesses', 'Misc High Value', 1100, 30, 'commercial'],
    ['scale content production with ai', 'Misc High Value', 800, 26, 'commercial'],
    ['ai tool for content scale', 'Misc High Value', 600, 22, 'commercial'],
    ['ai post creator for brands', 'Misc High Value', 1300, 32, 'commercial'],
    ['brand social media content creator ai', 'Misc High Value', 1000, 29, 'commercial'],
    ['ai that knows what to post', 'Misc High Value', 700, 24, 'commercial'],
    ['social media content idea generator', 'Misc High Value', 3200, 50, 'commercial'],
    ['ai generate weekly social media plan', 'Misc High Value', 900, 27, 'commercial'],
    ['social media post ideas for this week', 'Misc High Value', 2400, 44, 'informational'],
    ['post ideas small business instagram', 'Misc High Value', 2800, 46, 'informational'],
    ['what to post on instagram for business', 'Misc High Value', 3600, 52, 'informational'],
    ['what to post on linkedin this week', 'Misc High Value', 2100, 41, 'informational'],
    ['social media caption ideas', 'Misc High Value', 4200, 56, 'informational'],
    ['ai caption ideas for business', 'Misc High Value', 1600, 36, 'commercial'],
    ['how to come up with social media content', 'Misc High Value', 3100, 49, 'informational'],
    ['content ideas when you have nothing to post', 'Misc High Value', 2400, 44, 'informational'],
    ['ai help me post on social media', 'Misc High Value', 1800, 38, 'commercial'],
    ['use ai for social media for free', 'Misc High Value', 2600, 46, 'commercial'],
    ['try ai social media for free', 'Misc High Value', 1900, 40, 'commercial'],
    ['free trial social media ai no credit card', 'Misc High Value', 1400, 34, 'commercial'],
    ['social media tool 7 days free', 'Misc High Value', 1100, 30, 'commercial'],
    ['nativpost free', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost sign up', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost how it works', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost features', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost paystack', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost for africa', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost anti slop filter', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost content studio', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost social scheduler', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost team', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost connect', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost whatsapp bot', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost telegram', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost login', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost dashboard', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost app', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost ai engine', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost ugc video', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost carousel', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost analytics', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost media library', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost enterprise', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost pro plan', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost vs jasper', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost vs later', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost vs socialbee', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost launch', 'NativPost Brand', 0, 10, 'informational'],
    ['what is nativpost', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost product hunt', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost vs feedhive', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost test', 'NativPost Brand', 0, 10, 'informational'],
    ['sign up nativpost', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost contact', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost support', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost cancellation', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost refund policy', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost growth hack', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost setup', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost onboarding', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost brand profile', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost instagram', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost facebook', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost youtube', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost threads', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost pinterest', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost twitter x', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost coupon code', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost discount', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost affiliate program', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost partner', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost blog', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost news', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost update', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost guide', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost tutorial', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost vs contentstudio', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost vs sprout social', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost review 2026', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost honest review', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost is it legit', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost alternatives 2026', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost cost', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost monthly cost', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost trial review', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost vs hootsuite', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost competitor', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost founders', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost company', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost lagos', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost africa startup', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost b2b', 'NativPost Brand', 0, 10, 'commercial'],
    ['nativpost for agencies review', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost help', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost documentation', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost how to use', 'NativPost Brand', 0, 10, 'informational'],
    ['nativpost worth it 2026', 'NativPost Brand', 0, 10, 'informational'],
    ['ai social media tool 2026 review', 'Pricing & Reviews', 1800, 37, 'informational'],
    ['social media tool monthly vs annual', 'Pricing & Reviews', 700, 23, 'commercial'],
    ['pay monthly social media tool', 'Pricing & Reviews', 900, 26, 'commercial'],
    ['social media tool cancel anytime', 'Pricing & Reviews', 800, 25, 'commercial'],
    ['no contract social media management tool', 'Pricing & Reviews', 950, 27, 'commercial'],
    ['social media tool risk free trial', 'Pricing & Reviews', 700, 23, 'commercial'],
];

// ---------------------------------------------------------------------------
// MAIN
// ---------------------------------------------------------------------------
(async () => {
    console.log(`\nNativPost Keyword Seeder — ${KEYWORDS.length} keywords\n`);
    const db = await mysql.createConnection(DB);

    let inserted = 0;
    let updated = 0;
    let errors = 0;

    const SQL = `
    INSERT INTO keywords
      (site_id, keyword, cluster_name, volume, difficulty, priority_score, source, intent, last_updated)
    VALUES (NULL, ?, ?, ?, ?, ?, 'seed', ?, NOW())
    ON DUPLICATE KEY UPDATE
      cluster_name   = VALUES(cluster_name),
      volume         = GREATEST(volume, VALUES(volume)),
      difficulty     = VALUES(difficulty),
      priority_score = GREATEST(priority_score, VALUES(priority_score)),
      intent         = VALUES(intent),
      last_updated   = NOW()
  `;

    function score(volume, difficulty) {
        return priorityScore({ volume, difficulty, position: 50 });
    }

    for (const [kw, cluster, vol, diff, intent] of KEYWORDS) {
        try {
            const [result] = await db.execute(SQL, [
                kw, cluster, vol, diff, score(vol, diff), intent
            ]);
            if (result.affectedRows === 1) inserted++;
            else if (result.affectedRows === 2) updated++;
        } catch (e) {
            console.error(`  ✗  ${kw}: ${e.message}`);
            errors++;
        }
    }

    await db.end();

    console.log(`Done.`);
    console.log(`  ✓  Inserted : ${inserted}`);
    console.log(`  ↻  Updated  : ${updated}`);
    console.log(`  ✗  Errors   : ${errors}`);
    console.log(`\nRefresh the Keywords page at https://seo.nativpost.com/keywords\n`);
})();
// NOTE: additional keywords appended below — see full list in KEYWORDS array above